// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\tb_CameraIO\CameraIO_ip_src_sdo_master_sel.v
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// Copyright (c) 2023, Alexei Evsenin, evsenin@gmail.com
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: CameraIO_ip_src_sdo_master_sel
// Source Path: tb_CameraIO/CameraIO/TCA9548A/sdo_master_sel
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module CameraIO_ip_src_sdo_master_sel
          (w,
           v_0,
           v_1,
           v_2,
           v_3,
           v_4,
           v_5,
           v_6,
           v_7,
           u,
           y);


  input   w;
  input   v_0;  // boolean
  input   v_1;  // boolean
  input   v_2;  // boolean
  input   v_3;  // boolean
  input   v_4;  // boolean
  input   v_5;  // boolean
  input   v_6;  // boolean
  input   v_7;  // boolean
  input   [7:0] u;  // uint8
  output  y;


  wire [0:7] v;  // boolean [8]
  reg  y_1;
  reg  aVarTruthTableCondition_1;
  reg  aVarTruthTableCondition_2;
  reg  aVarTruthTableCondition_3;
  reg  aVarTruthTableCondition_4;
  reg  aVarTruthTableCondition_5;
  reg  aVarTruthTableCondition_6;
  reg  aVarTruthTableCondition_7;
  reg  aVarTruthTableCondition_8;


  assign v[0] = v_0;
  assign v[1] = v_1;
  assign v[2] = v_2;
  assign v[3] = v_3;
  assign v[4] = v_4;
  assign v[5] = v_5;
  assign v[6] = v_6;
  assign v[7] = v_7;

  always @* begin
    //Truth Table Function 'CameraIO/TCA9548A/sdo_master_sel'
    // sel 1
    //Condition '#1'
    aVarTruthTableCondition_1 = u[0] != 1'b0;
    // sel 2
    //Condition '#2'
    aVarTruthTableCondition_2 = u[1] != 1'b0;
    // sel 3
    //Condition '#3'
    aVarTruthTableCondition_3 = u[2] != 1'b0;
    // sel 4
    //Condition '#4'
    aVarTruthTableCondition_4 = u[3] != 1'b0;
    // sel 5
    //Condition '#5'
    aVarTruthTableCondition_5 = u[4] != 1'b0;
    // sel 6
    //Condition '#6'
    aVarTruthTableCondition_6 = u[5] != 1'b0;
    // sel 7
    //Condition '#7'
    aVarTruthTableCondition_7 = u[6] != 1'b0;
    // sel 8
    //Condition '#8'
    aVarTruthTableCondition_8 = u[7] != 1'b0;
    if (aVarTruthTableCondition_1) begin
      //Decision 'D1'
      // sel 1
      //Action '1'
      y_1 = v[0];
    end
    else if (aVarTruthTableCondition_2) begin
      //Decision 'D2'
      // sel 2
      //Action '2'
      y_1 = v[1];
    end
    else if (aVarTruthTableCondition_3) begin
      //Decision 'D3'
      // sel 3
      //Action '3'
      y_1 = v[2];
    end
    else if (aVarTruthTableCondition_4) begin
      //Decision 'D4'
      // sel 4
      //Action '4'
      y_1 = v[3];
    end
    else if (aVarTruthTableCondition_5) begin
      //Decision 'D5'
      // sel 5
      //Action '5'
      y_1 = v[4];
    end
    else if (aVarTruthTableCondition_6) begin
      //Decision 'D6'
      // sel 6
      //Action '6'
      y_1 = v[5];
    end
    else if (aVarTruthTableCondition_7) begin
      //Decision 'D7'
      // sel 7
      //Action '7'
      y_1 = v[6];
    end
    else if (aVarTruthTableCondition_8) begin
      //Decision 'D8'
      // sel 8
      //Action '8'
      y_1 = v[7];
    end
    else begin
      //Decision 'D9'
      // Default
      // sel none
      //Action '9'
      y_1 = 1'b1;
    end
  end


  assign y = y_1;

endmodule  // CameraIO_ip_src_sdo_master_sel

