// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\tb_CameraIO\CameraIO_ip_dut.v
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// Copyright (c) 2023, Alexei Evsenin, evsenin@gmail.com
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: CameraIO_ip_dut
// Source Path: CameraIO_ip/CameraIO_ip_dut
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module CameraIO_ip_dut
          (clk,
           reset_x,
           Muxer_sdi,
           Muxer_sci,
           Expander_sdi,
           Expander_sci,
           Cam1_sdi,
           Cam2_sdi,
           Cam3_sdi,
           Expander_nRST,
           CAM_Master_CLK,
           GPIO27_PWM2,
           Cam1_sci,
           Cam2_sci,
           Cam3_sci,
           AXI_CameraIO_Control,
           Expander_sdoen,
           Expander_scoen,
           Muxer_sdoen,
           Muxer_scoen,
           CAM1_nCS,
           CAM1_nRST,
           CAM1_PWDN,
           CAM1_FLASH,
           CAM2_nCS,
           CAM2_nRST,
           CAM2_PWDN,
           CAM2_FLASH,
           CAM3_nCS,
           CAM3_nRST,
           CAM3_PWDN,
           CAM3_FLASH,
           Cam3_sdoen,
           Cam3_scoen,
           Cam2_sdoen,
           Cam2_scoen,
           Cam1_sdoen,
           Cam1_scoen,
           Expander_nINT,
           AXI_CameraIO_Status,
           CAM1_TRIG,
           CAM2_TRIG,
           CAM3_TRIG,
           RADAR0_enable,
           RADAR1_enable,
           AXI_ExpanderValue,
           AXI_MuxerValue);


  input   clk;
  input   reset_x;
  input   Muxer_sdi;  // ufix1
  input   Muxer_sci;  // ufix1
  input   Expander_sdi;  // ufix1
  input   Expander_sci;  // ufix1
  input   Cam1_sdi;  // ufix1
  input   Cam2_sdi;  // ufix1
  input   Cam3_sdi;  // ufix1
  input   Expander_nRST;  // ufix1
  input   CAM_Master_CLK;  // ufix1
  input   GPIO27_PWM2;  // ufix1
  input   Cam1_sci;  // ufix1
  input   Cam2_sci;  // ufix1
  input   Cam3_sci;  // ufix1
  input   [31:0] AXI_CameraIO_Control;  // ufix32
  output  Expander_sdoen;  // ufix1
  output  Expander_scoen;  // ufix1
  output  Muxer_sdoen;  // ufix1
  output  Muxer_scoen;  // ufix1
  output  CAM1_nCS;  // ufix1
  output  CAM1_nRST;  // ufix1
  output  CAM1_PWDN;  // ufix1
  output  CAM1_FLASH;  // ufix1
  output  CAM2_nCS;  // ufix1
  output  CAM2_nRST;  // ufix1
  output  CAM2_PWDN;  // ufix1
  output  CAM2_FLASH;  // ufix1
  output  CAM3_nCS;  // ufix1
  output  CAM3_nRST;  // ufix1
  output  CAM3_PWDN;  // ufix1
  output  CAM3_FLASH;  // ufix1
  output  Cam3_sdoen;  // ufix1
  output  Cam3_scoen;  // ufix1
  output  Cam2_sdoen;  // ufix1
  output  Cam2_scoen;  // ufix1
  output  Cam1_sdoen;  // ufix1
  output  Cam1_scoen;  // ufix1
  output  Expander_nINT;  // ufix1
  output  [11:0] AXI_CameraIO_Status;  // ufix12
  output  CAM1_TRIG;  // ufix1
  output  CAM2_TRIG;  // ufix1
  output  CAM3_TRIG;  // ufix1
  output  RADAR0_enable;  // ufix1
  output  RADAR1_enable;  // ufix1
  output  [23:0] AXI_ExpanderValue;  // ufix24
  output  [7:0] AXI_MuxerValue;  // ufix8


  wire Expander_sdoen_sig;  // ufix1
  wire Expander_scoen_sig;  // ufix1
  wire Muxer_sdoen_sig;  // ufix1
  wire Muxer_scoen_sig;  // ufix1
  wire CAM1_nCS_sig;  // ufix1
  wire CAM1_nRST_sig;  // ufix1
  wire CAM1_PWDN_sig;  // ufix1
  wire CAM1_FLASH_sig;  // ufix1
  wire CAM2_nCS_sig;  // ufix1
  wire CAM2_nRST_sig;  // ufix1
  wire CAM2_PWDN_sig;  // ufix1
  wire CAM2_FLASH_sig;  // ufix1
  wire CAM3_nCS_sig;  // ufix1
  wire CAM3_nRST_sig;  // ufix1
  wire CAM3_PWDN_sig;  // ufix1
  wire CAM3_FLASH_sig;  // ufix1
  wire Cam3_sdoen_sig;  // ufix1
  wire Cam3_scoen_sig;  // ufix1
  wire Cam2_sdoen_sig;  // ufix1
  wire Cam2_scoen_sig;  // ufix1
  wire Cam1_sdoen_sig;  // ufix1
  wire Cam1_scoen_sig;  // ufix1
  wire Expander_nINT_sig;  // ufix1
  wire [11:0] AXI_CameraIO_Status_sig;  // ufix12
  wire CAM1_TRIG_sig;  // ufix1
  wire CAM2_TRIG_sig;  // ufix1
  wire CAM3_TRIG_sig;  // ufix1
  wire RADAR0_enable_sig;  // ufix1
  wire RADAR1_enable_sig;  // ufix1
  wire [23:0] AXI_ExpanderValue_sig;  // ufix24
  wire [7:0] AXI_MuxerValue_sig;  // ufix8


  CameraIO_ip_src_CameraIO u_CameraIO_ip_src_CameraIO (.clk(clk),
                                                       .reset_x(reset_x),
                                                       .Muxer_sdi(Muxer_sdi),  // ufix1
                                                       .Muxer_sci(Muxer_sci),  // ufix1
                                                       .Expander_sdi(Expander_sdi),  // ufix1
                                                       .Expander_sci(Expander_sci),  // ufix1
                                                       .Cam1_sdi(Cam1_sdi),  // ufix1
                                                       .Cam2_sdi(Cam2_sdi),  // ufix1
                                                       .Cam3_sdi(Cam3_sdi),  // ufix1
                                                       .Expander_nRST(Expander_nRST),  // ufix1
                                                       .CAM_Master_CLK(CAM_Master_CLK),  // ufix1
                                                       .GPIO27_PWM2(GPIO27_PWM2),  // ufix1
                                                       .Cam1_sci(Cam1_sci),  // ufix1
                                                       .Cam2_sci(Cam2_sci),  // ufix1
                                                       .Cam3_sci(Cam3_sci),  // ufix1
                                                       .AXI_CameraIO_Control(AXI_CameraIO_Control),  // ufix32
                                                       .Expander_sdoen(Expander_sdoen_sig),  // ufix1
                                                       .Expander_scoen(Expander_scoen_sig),  // ufix1
                                                       .Muxer_sdoen(Muxer_sdoen_sig),  // ufix1
                                                       .Muxer_scoen(Muxer_scoen_sig),  // ufix1
                                                       .CAM1_nCS(CAM1_nCS_sig),  // ufix1
                                                       .CAM1_nRST(CAM1_nRST_sig),  // ufix1
                                                       .CAM1_PWDN(CAM1_PWDN_sig),  // ufix1
                                                       .CAM1_FLASH(CAM1_FLASH_sig),  // ufix1
                                                       .CAM2_nCS(CAM2_nCS_sig),  // ufix1
                                                       .CAM2_nRST(CAM2_nRST_sig),  // ufix1
                                                       .CAM2_PWDN(CAM2_PWDN_sig),  // ufix1
                                                       .CAM2_FLASH(CAM2_FLASH_sig),  // ufix1
                                                       .CAM3_nCS(CAM3_nCS_sig),  // ufix1
                                                       .CAM3_nRST(CAM3_nRST_sig),  // ufix1
                                                       .CAM3_PWDN(CAM3_PWDN_sig),  // ufix1
                                                       .CAM3_FLASH(CAM3_FLASH_sig),  // ufix1
                                                       .Cam3_sdoen(Cam3_sdoen_sig),  // ufix1
                                                       .Cam3_scoen(Cam3_scoen_sig),  // ufix1
                                                       .Cam2_sdoen(Cam2_sdoen_sig),  // ufix1
                                                       .Cam2_scoen(Cam2_scoen_sig),  // ufix1
                                                       .Cam1_sdoen(Cam1_sdoen_sig),  // ufix1
                                                       .Cam1_scoen(Cam1_scoen_sig),  // ufix1
                                                       .Expander_nINT(Expander_nINT_sig),  // ufix1
                                                       .AXI_CameraIO_Status(AXI_CameraIO_Status_sig),  // ufix12
                                                       .CAM1_TRIG(CAM1_TRIG_sig),  // ufix1
                                                       .CAM2_TRIG(CAM2_TRIG_sig),  // ufix1
                                                       .CAM3_TRIG(CAM3_TRIG_sig),  // ufix1
                                                       .RADAR0_enable(RADAR0_enable_sig),  // ufix1
                                                       .RADAR1_enable(RADAR1_enable_sig),  // ufix1
                                                       .AXI_ExpanderValue(AXI_ExpanderValue_sig),  // ufix24
                                                       .AXI_MuxerValue(AXI_MuxerValue_sig)  // ufix8
                                                       );

  assign Expander_sdoen = Expander_sdoen_sig;

  assign Expander_scoen = Expander_scoen_sig;

  assign Muxer_sdoen = Muxer_sdoen_sig;

  assign Muxer_scoen = Muxer_scoen_sig;

  assign CAM1_nCS = CAM1_nCS_sig;

  assign CAM1_nRST = CAM1_nRST_sig;

  assign CAM1_PWDN = CAM1_PWDN_sig;

  assign CAM1_FLASH = CAM1_FLASH_sig;

  assign CAM2_nCS = CAM2_nCS_sig;

  assign CAM2_nRST = CAM2_nRST_sig;

  assign CAM2_PWDN = CAM2_PWDN_sig;

  assign CAM2_FLASH = CAM2_FLASH_sig;

  assign CAM3_nCS = CAM3_nCS_sig;

  assign CAM3_nRST = CAM3_nRST_sig;

  assign CAM3_PWDN = CAM3_PWDN_sig;

  assign CAM3_FLASH = CAM3_FLASH_sig;

  assign Cam3_sdoen = Cam3_sdoen_sig;

  assign Cam3_scoen = Cam3_scoen_sig;

  assign Cam2_sdoen = Cam2_sdoen_sig;

  assign Cam2_scoen = Cam2_scoen_sig;

  assign Cam1_sdoen = Cam1_sdoen_sig;

  assign Cam1_scoen = Cam1_scoen_sig;

  assign Expander_nINT = Expander_nINT_sig;

  assign AXI_CameraIO_Status = AXI_CameraIO_Status_sig;

  assign CAM1_TRIG = CAM1_TRIG_sig;

  assign CAM2_TRIG = CAM2_TRIG_sig;

  assign CAM3_TRIG = CAM3_TRIG_sig;

  assign RADAR0_enable = RADAR0_enable_sig;

  assign RADAR1_enable = RADAR1_enable_sig;

  assign AXI_ExpanderValue = AXI_ExpanderValue_sig;

  assign AXI_MuxerValue = AXI_MuxerValue_sig;

endmodule  // CameraIO_ip_dut

