// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\tb_CameraIO\CameraIO_ip_src_pulse.v
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// Copyright (c) 2023, Alexei Evsenin, evsenin@gmail.com
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: CameraIO_ip_src_pulse
// Source Path: tb_CameraIO/CameraIO/TCA9548A/pulse
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module CameraIO_ip_src_pulse
          (clk,
           reset_x,
           valid,
           rise,
           fall);


  input   clk;
  input   reset_x;
  input   valid;
  output  rise;
  output  fall;


  reg  Delay_out1;
  wire NOT_out1;
  wire AND_out1;
  wire NOT1_out1;
  wire AND1_out1;


  always @(posedge clk or posedge reset_x)
    begin : Delay_process
      if (reset_x == 1'b1) begin
        Delay_out1 <= 1'b0;
      end
      else begin
        Delay_out1 <= valid;
      end
    end


  assign NOT_out1 =  ~ Delay_out1;


  assign AND_out1 = valid & NOT_out1;


  assign rise = AND_out1;

  assign NOT1_out1 =  ~ valid;


  assign AND1_out1 = Delay_out1 & NOT1_out1;


  assign fall = AND1_out1;

endmodule  // CameraIO_ip_src_pulse

