// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\tb_CameraIO\CameraIO_ip.v
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: -1
// Target subsystem base rate: -1
// 
// Copyright (c) 2023, Alexei Evsenin, evsenin@gmail.com
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: CameraIO_ip
// Source Path: CameraIO_ip
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module CameraIO_ip
          (IPCORE_CLK,
           IPCORE_RESETN,
           Muxer_sdi,
           Muxer_sci,
           Expander_sdi,
           Expander_sci,
           Cam1_sdi,
           Cam2_sdi,
           Cam3_sdi,
           Expander_nRST,
           CAM_Master_CLK,
           GPIO27_PWM2,
           Cam1_sci,
           Cam2_sci,
           Cam3_sci,
           AXI4_ACLK,
           AXI4_ARESETN,
           AXI4_AWID,
           AXI4_AWADDR,
           AXI4_AWLEN,
           AXI4_AWSIZE,
           AXI4_AWBURST,
           AXI4_AWLOCK,
           AXI4_AWCACHE,
           AXI4_AWPROT,
           AXI4_AWVALID,
           AXI4_WDATA,
           AXI4_WSTRB,
           AXI4_WLAST,
           AXI4_WVALID,
           AXI4_BREADY,
           AXI4_ARID,
           AXI4_ARADDR,
           AXI4_ARLEN,
           AXI4_ARSIZE,
           AXI4_ARBURST,
           AXI4_ARLOCK,
           AXI4_ARCACHE,
           AXI4_ARPROT,
           AXI4_ARVALID,
           AXI4_RREADY,
           Expander_sdoen,
           Expander_scoen,
           Muxer_sdoen,
           Muxer_scoen,
           CAM1_nCS,
           CAM1_nRST,
           CAM1_PWDN,
           CAM1_FLASH,
           CAM2_nCS,
           CAM2_nRST,
           CAM2_PWDN,
           CAM2_FLASH,
           CAM3_nCS,
           CAM3_nRST,
           CAM3_PWDN,
           CAM3_FLASH,
           Cam3_sdoen,
           Cam3_scoen,
           Cam2_sdoen,
           Cam2_scoen,
           Cam1_sdoen,
           Cam1_scoen,
           Expander_nINT,
           CAM1_TRIG,
           CAM2_TRIG,
           CAM3_TRIG,
           RADAR0_enable,
           RADAR1_enable,
           AXI4_AWREADY,
           AXI4_WREADY,
           AXI4_BID,
           AXI4_BRESP,
           AXI4_BVALID,
           AXI4_ARREADY,
           AXI4_RID,
           AXI4_RDATA,
           AXI4_RRESP,
           AXI4_RLAST,
           AXI4_RVALID);


  input   IPCORE_CLK;  // ufix1
  input   IPCORE_RESETN;  // ufix1
  input   Muxer_sdi;  // ufix1
  input   Muxer_sci;  // ufix1
  input   Expander_sdi;  // ufix1
  input   Expander_sci;  // ufix1
  input   Cam1_sdi;  // ufix1
  input   Cam2_sdi;  // ufix1
  input   Cam3_sdi;  // ufix1
  input   Expander_nRST;  // ufix1
  input   CAM_Master_CLK;  // ufix1
  input   GPIO27_PWM2;  // ufix1
  input   Cam1_sci;  // ufix1
  input   Cam2_sci;  // ufix1
  input   Cam3_sci;  // ufix1
  input   AXI4_ACLK;  // ufix1
  input   AXI4_ARESETN;  // ufix1
  input   [15:0] AXI4_AWID;  // ufix16
  input   [15:0] AXI4_AWADDR;  // ufix16
  input   [7:0] AXI4_AWLEN;  // ufix8
  input   [2:0] AXI4_AWSIZE;  // ufix3
  input   [1:0] AXI4_AWBURST;  // ufix2
  input   AXI4_AWLOCK;  // ufix1
  input   [3:0] AXI4_AWCACHE;  // ufix4
  input   [2:0] AXI4_AWPROT;  // ufix3
  input   AXI4_AWVALID;  // ufix1
  input   [31:0] AXI4_WDATA;  // ufix32
  input   [3:0] AXI4_WSTRB;  // ufix4
  input   AXI4_WLAST;  // ufix1
  input   AXI4_WVALID;  // ufix1
  input   AXI4_BREADY;  // ufix1
  input   [15:0] AXI4_ARID;  // ufix16
  input   [15:0] AXI4_ARADDR;  // ufix16
  input   [7:0] AXI4_ARLEN;  // ufix8
  input   [2:0] AXI4_ARSIZE;  // ufix3
  input   [1:0] AXI4_ARBURST;  // ufix2
  input   AXI4_ARLOCK;  // ufix1
  input   [3:0] AXI4_ARCACHE;  // ufix4
  input   [2:0] AXI4_ARPROT;  // ufix3
  input   AXI4_ARVALID;  // ufix1
  input   AXI4_RREADY;  // ufix1
  output  Expander_sdoen;  // ufix1
  output  Expander_scoen;  // ufix1
  output  Muxer_sdoen;  // ufix1
  output  Muxer_scoen;  // ufix1
  output  CAM1_nCS;  // ufix1
  output  CAM1_nRST;  // ufix1
  output  CAM1_PWDN;  // ufix1
  output  CAM1_FLASH;  // ufix1
  output  CAM2_nCS;  // ufix1
  output  CAM2_nRST;  // ufix1
  output  CAM2_PWDN;  // ufix1
  output  CAM2_FLASH;  // ufix1
  output  CAM3_nCS;  // ufix1
  output  CAM3_nRST;  // ufix1
  output  CAM3_PWDN;  // ufix1
  output  CAM3_FLASH;  // ufix1
  output  Cam3_sdoen;  // ufix1
  output  Cam3_scoen;  // ufix1
  output  Cam2_sdoen;  // ufix1
  output  Cam2_scoen;  // ufix1
  output  Cam1_sdoen;  // ufix1
  output  Cam1_scoen;  // ufix1
  output  Expander_nINT;  // ufix1
  output  CAM1_TRIG;  // ufix1
  output  CAM2_TRIG;  // ufix1
  output  CAM3_TRIG;  // ufix1
  output  RADAR0_enable;  // ufix1
  output  RADAR1_enable;  // ufix1
  output  AXI4_AWREADY;  // ufix1
  output  AXI4_WREADY;  // ufix1
  output  [15:0] AXI4_BID;  // ufix16
  output  [1:0] AXI4_BRESP;  // ufix2
  output  AXI4_BVALID;  // ufix1
  output  AXI4_ARREADY;  // ufix1
  output  [15:0] AXI4_RID;  // ufix16
  output  [31:0] AXI4_RDATA;  // ufix32
  output  [1:0] AXI4_RRESP;  // ufix2
  output  AXI4_RLAST;  // ufix1
  output  AXI4_RVALID;  // ufix1


  wire reset_x;
  wire [31:0] ip_timestamp;  // ufix32
  wire reset_cm;  // ufix1
  wire reset_internal;  // ufix1
  wire reset_before_sync;  // ufix1
  wire [23:0] AXI_ExpanderValue_sig;  // ufix24
  wire [11:0] AXI_CameraIO_Status_sig;  // ufix12
  wire [7:0] AXI_MuxerValue_sig;  // ufix8
  wire [31:0] write_AXI_CameraIO_Control;  // ufix32
  wire Expander_sdoen_sig;  // ufix1
  wire Expander_scoen_sig;  // ufix1
  wire Muxer_sdoen_sig;  // ufix1
  wire Muxer_scoen_sig;  // ufix1
  wire CAM1_nCS_sig;  // ufix1
  wire CAM1_nRST_sig;  // ufix1
  wire CAM1_PWDN_sig;  // ufix1
  wire CAM1_FLASH_sig;  // ufix1
  wire CAM2_nCS_sig;  // ufix1
  wire CAM2_nRST_sig;  // ufix1
  wire CAM2_PWDN_sig;  // ufix1
  wire CAM2_FLASH_sig;  // ufix1
  wire CAM3_nCS_sig;  // ufix1
  wire CAM3_nRST_sig;  // ufix1
  wire CAM3_PWDN_sig;  // ufix1
  wire CAM3_FLASH_sig;  // ufix1
  wire Cam3_sdoen_sig;  // ufix1
  wire Cam3_scoen_sig;  // ufix1
  wire Cam2_sdoen_sig;  // ufix1
  wire Cam2_scoen_sig;  // ufix1
  wire Cam1_sdoen_sig;  // ufix1
  wire Cam1_scoen_sig;  // ufix1
  wire Expander_nINT_sig;  // ufix1
  wire CAM1_TRIG_sig;  // ufix1
  wire CAM2_TRIG_sig;  // ufix1
  wire CAM3_TRIG_sig;  // ufix1
  wire RADAR0_enable_sig;  // ufix1
  wire RADAR1_enable_sig;  // ufix1


  assign ip_timestamp = 32'b10001001001001111001000111101011;



  assign reset_cm =  ~ IPCORE_RESETN;



  assign reset_before_sync = reset_cm | reset_internal;



  CameraIO_ip_reset_sync u_CameraIO_ip_reset_sync_inst (.clk(IPCORE_CLK),  // ufix1
                                                        .reset_in(reset_before_sync),  // ufix1
                                                        .reset_out(reset_x)
                                                        );

  CameraIO_ip_axi4 u_CameraIO_ip_axi4_inst (.reset_x(reset_x),
                                            .AXI4_ACLK(AXI4_ACLK),  // ufix1
                                            .AXI4_ARESETN(AXI4_ARESETN),  // ufix1
                                            .AXI4_AWID(AXI4_AWID),  // ufix16
                                            .AXI4_AWADDR(AXI4_AWADDR),  // ufix16
                                            .AXI4_AWLEN(AXI4_AWLEN),  // ufix8
                                            .AXI4_AWSIZE(AXI4_AWSIZE),  // ufix3
                                            .AXI4_AWBURST(AXI4_AWBURST),  // ufix2
                                            .AXI4_AWLOCK(AXI4_AWLOCK),  // ufix1
                                            .AXI4_AWCACHE(AXI4_AWCACHE),  // ufix4
                                            .AXI4_AWPROT(AXI4_AWPROT),  // ufix3
                                            .AXI4_AWVALID(AXI4_AWVALID),  // ufix1
                                            .AXI4_WDATA(AXI4_WDATA),  // ufix32
                                            .AXI4_WSTRB(AXI4_WSTRB),  // ufix4
                                            .AXI4_WLAST(AXI4_WLAST),  // ufix1
                                            .AXI4_WVALID(AXI4_WVALID),  // ufix1
                                            .AXI4_BREADY(AXI4_BREADY),  // ufix1
                                            .AXI4_ARID(AXI4_ARID),  // ufix16
                                            .AXI4_ARADDR(AXI4_ARADDR),  // ufix16
                                            .AXI4_ARLEN(AXI4_ARLEN),  // ufix8
                                            .AXI4_ARSIZE(AXI4_ARSIZE),  // ufix3
                                            .AXI4_ARBURST(AXI4_ARBURST),  // ufix2
                                            .AXI4_ARLOCK(AXI4_ARLOCK),  // ufix1
                                            .AXI4_ARCACHE(AXI4_ARCACHE),  // ufix4
                                            .AXI4_ARPROT(AXI4_ARPROT),  // ufix3
                                            .AXI4_ARVALID(AXI4_ARVALID),  // ufix1
                                            .AXI4_RREADY(AXI4_RREADY),  // ufix1
                                            .read_ip_timestamp(ip_timestamp),  // ufix32
                                            .read_AXI_ExpanderValue(AXI_ExpanderValue_sig),  // ufix24
                                            .read_AXI_CameraIO_Status(AXI_CameraIO_Status_sig),  // ufix12
                                            .read_AXI_MuxerValue(AXI_MuxerValue_sig),  // ufix8
                                            .AXI4_AWREADY(AXI4_AWREADY),  // ufix1
                                            .AXI4_WREADY(AXI4_WREADY),  // ufix1
                                            .AXI4_BID(AXI4_BID),  // ufix16
                                            .AXI4_BRESP(AXI4_BRESP),  // ufix2
                                            .AXI4_BVALID(AXI4_BVALID),  // ufix1
                                            .AXI4_ARREADY(AXI4_ARREADY),  // ufix1
                                            .AXI4_RID(AXI4_RID),  // ufix16
                                            .AXI4_RDATA(AXI4_RDATA),  // ufix32
                                            .AXI4_RRESP(AXI4_RRESP),  // ufix2
                                            .AXI4_RLAST(AXI4_RLAST),  // ufix1
                                            .AXI4_RVALID(AXI4_RVALID),  // ufix1
                                            .write_AXI_CameraIO_Control(write_AXI_CameraIO_Control),  // ufix32
                                            .reset_internal(reset_internal)  // ufix1
                                            );

  CameraIO_ip_dut u_CameraIO_ip_dut_inst (.clk(IPCORE_CLK),  // ufix1
                                          .reset_x(reset_x),
                                          .Muxer_sdi(Muxer_sdi),  // ufix1
                                          .Muxer_sci(Muxer_sci),  // ufix1
                                          .Expander_sdi(Expander_sdi),  // ufix1
                                          .Expander_sci(Expander_sci),  // ufix1
                                          .Cam1_sdi(Cam1_sdi),  // ufix1
                                          .Cam2_sdi(Cam2_sdi),  // ufix1
                                          .Cam3_sdi(Cam3_sdi),  // ufix1
                                          .Expander_nRST(Expander_nRST),  // ufix1
                                          .CAM_Master_CLK(CAM_Master_CLK),  // ufix1
                                          .GPIO27_PWM2(GPIO27_PWM2),  // ufix1
                                          .Cam1_sci(Cam1_sci),  // ufix1
                                          .Cam2_sci(Cam2_sci),  // ufix1
                                          .Cam3_sci(Cam3_sci),  // ufix1
                                          .AXI_CameraIO_Control(write_AXI_CameraIO_Control),  // ufix32
                                          .Expander_sdoen(Expander_sdoen_sig),  // ufix1
                                          .Expander_scoen(Expander_scoen_sig),  // ufix1
                                          .Muxer_sdoen(Muxer_sdoen_sig),  // ufix1
                                          .Muxer_scoen(Muxer_scoen_sig),  // ufix1
                                          .CAM1_nCS(CAM1_nCS_sig),  // ufix1
                                          .CAM1_nRST(CAM1_nRST_sig),  // ufix1
                                          .CAM1_PWDN(CAM1_PWDN_sig),  // ufix1
                                          .CAM1_FLASH(CAM1_FLASH_sig),  // ufix1
                                          .CAM2_nCS(CAM2_nCS_sig),  // ufix1
                                          .CAM2_nRST(CAM2_nRST_sig),  // ufix1
                                          .CAM2_PWDN(CAM2_PWDN_sig),  // ufix1
                                          .CAM2_FLASH(CAM2_FLASH_sig),  // ufix1
                                          .CAM3_nCS(CAM3_nCS_sig),  // ufix1
                                          .CAM3_nRST(CAM3_nRST_sig),  // ufix1
                                          .CAM3_PWDN(CAM3_PWDN_sig),  // ufix1
                                          .CAM3_FLASH(CAM3_FLASH_sig),  // ufix1
                                          .Cam3_sdoen(Cam3_sdoen_sig),  // ufix1
                                          .Cam3_scoen(Cam3_scoen_sig),  // ufix1
                                          .Cam2_sdoen(Cam2_sdoen_sig),  // ufix1
                                          .Cam2_scoen(Cam2_scoen_sig),  // ufix1
                                          .Cam1_sdoen(Cam1_sdoen_sig),  // ufix1
                                          .Cam1_scoen(Cam1_scoen_sig),  // ufix1
                                          .Expander_nINT(Expander_nINT_sig),  // ufix1
                                          .AXI_CameraIO_Status(AXI_CameraIO_Status_sig),  // ufix12
                                          .CAM1_TRIG(CAM1_TRIG_sig),  // ufix1
                                          .CAM2_TRIG(CAM2_TRIG_sig),  // ufix1
                                          .CAM3_TRIG(CAM3_TRIG_sig),  // ufix1
                                          .RADAR0_enable(RADAR0_enable_sig),  // ufix1
                                          .RADAR1_enable(RADAR1_enable_sig),  // ufix1
                                          .AXI_ExpanderValue(AXI_ExpanderValue_sig),  // ufix24
                                          .AXI_MuxerValue(AXI_MuxerValue_sig)  // ufix8
                                          );

  assign Expander_sdoen = Expander_sdoen_sig;

  assign Expander_scoen = Expander_scoen_sig;

  assign Muxer_sdoen = Muxer_sdoen_sig;

  assign Muxer_scoen = Muxer_scoen_sig;

  assign CAM1_nCS = CAM1_nCS_sig;

  assign CAM1_nRST = CAM1_nRST_sig;

  assign CAM1_PWDN = CAM1_PWDN_sig;

  assign CAM1_FLASH = CAM1_FLASH_sig;

  assign CAM2_nCS = CAM2_nCS_sig;

  assign CAM2_nRST = CAM2_nRST_sig;

  assign CAM2_PWDN = CAM2_PWDN_sig;

  assign CAM2_FLASH = CAM2_FLASH_sig;

  assign CAM3_nCS = CAM3_nCS_sig;

  assign CAM3_nRST = CAM3_nRST_sig;

  assign CAM3_PWDN = CAM3_PWDN_sig;

  assign CAM3_FLASH = CAM3_FLASH_sig;

  assign Cam3_sdoen = Cam3_sdoen_sig;

  assign Cam3_scoen = Cam3_scoen_sig;

  assign Cam2_sdoen = Cam2_sdoen_sig;

  assign Cam2_scoen = Cam2_scoen_sig;

  assign Cam1_sdoen = Cam1_sdoen_sig;

  assign Cam1_scoen = Cam1_scoen_sig;

  assign Expander_nINT = Expander_nINT_sig;

  assign CAM1_TRIG = CAM1_TRIG_sig;

  assign CAM2_TRIG = CAM2_TRIG_sig;

  assign CAM3_TRIG = CAM3_TRIG_sig;

  assign RADAR0_enable = RADAR0_enable_sig;

  assign RADAR1_enable = RADAR1_enable_sig;

endmodule  // CameraIO_ip

