// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\tb_SYSTEM\SYSTEM_ip_src_pulse_10mks1.v
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// Copyright (c) 2023, Alexei Evsenin, evsenin@gmail.com
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: SYSTEM_ip_src_pulse_10mks1
// Source Path: tb_SYSTEM/SYSTEM/time_stamp_engine/pulse_10mks1
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module SYSTEM_ip_src_pulse_10mks1
          (clk,
           reset_x,
           PULSE_LEN,
           trigger,
           value,
           valid);


  input   clk;
  input   reset_x;
  input   [15:0] PULSE_LEN;  // uint16
  input   trigger;
  output  [15:0] value;  // uint16
  output  valid;


  wire [15:0] Pulse_extender_ctrl_out2;  // uint16
  wire Pulse_extender_ctrl_out1;
  wire [15:0] Pulse_extender_ctrl_out2deadOut;  // uint16


  assign Pulse_extender_ctrl_out2 = 16'b0000000000000000;



  assign value = Pulse_extender_ctrl_out2;

  SYSTEM_ip_src_Pulse_extender_ctrl u_Pulse_extender_ctrl (.clk(clk),
                                                           .reset_x(reset_x),
                                                           .PULSE_LEN(PULSE_LEN),  // uint16
                                                           .trigger(trigger),
                                                           .valid(Pulse_extender_ctrl_out1),
                                                           .value(Pulse_extender_ctrl_out2deadOut)  // uint16
                                                           );
  assign valid = Pulse_extender_ctrl_out1;

endmodule  // SYSTEM_ip_src_pulse_10mks1

