// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\tb_SYSTEM\SYSTEM_ip_axi4.v
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// Copyright (c) 2023, Alexei Evsenin, evsenin@gmail.com
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: SYSTEM_ip_axi4
// Source Path: SYSTEM_ip/SYSTEM_ip_axi4
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module SYSTEM_ip_axi4
          (reset_x,
           AXI4_ACLK,
           AXI4_ARESETN,
           AXI4_AWID,
           AXI4_AWADDR,
           AXI4_AWLEN,
           AXI4_AWSIZE,
           AXI4_AWBURST,
           AXI4_AWLOCK,
           AXI4_AWCACHE,
           AXI4_AWPROT,
           AXI4_AWVALID,
           AXI4_WDATA,
           AXI4_WSTRB,
           AXI4_WLAST,
           AXI4_WVALID,
           AXI4_BREADY,
           AXI4_ARID,
           AXI4_ARADDR,
           AXI4_ARLEN,
           AXI4_ARSIZE,
           AXI4_ARBURST,
           AXI4_ARLOCK,
           AXI4_ARCACHE,
           AXI4_ARPROT,
           AXI4_ARVALID,
           AXI4_RREADY,
           read_ip_timestamp,
           read_AXI_TVS_1000mV,
           read_AXI_TVS_1800mV,
           read_AXI_TVS_2500mV,
           read_AXI_TVS_tempr,
           read_AXI_SYS_STATUS,
           read_AXI_PWR_STATUS,
           read_AXI_PLL_STATUS,
           read_AXI_I2S_STATUS,
           read_AXI_CC_SPI_Rd,
           read_AXI_CC_STATUS,
           read_AXI_MonADC_STATUS,
           read_AXI_MonADC_SPI_Rd,
           read_AXI_Mon_12V,
           read_AXI_Mon_1V8,
           read_AXI_Mon_3V3,
           read_AXI_Mon_CurrentIn,
           read_AXI_Mon_VoltageIn,
           in_burst_axi4_master_rd,
           in_burst_axi4_master_wr,
           AXI4_AWREADY,
           AXI4_WREADY,
           AXI4_BID,
           AXI4_BRESP,
           AXI4_BVALID,
           AXI4_ARREADY,
           AXI4_RID,
           AXI4_RDATA,
           AXI4_RRESP,
           AXI4_RLAST,
           AXI4_RVALID,
           write_AXI4_Master_Rd_base_address,
           write_AXI4_Master_Wr_base_address,
           write_AXI_CC_SPI_Wr,
           write_AXI_CC_CONTROL,
           write_AXI_PWR_CONTROL,
           write_AXI_DDR_CONTROL,
           write_AXI_MonADC_SPI_Wr,
           write_AXI_MonADC_CONTROL,
           write_AXI_XAVIER_CONTROL,
           soft_reset_pending,
           reset_internal);


  input   reset_x;
  input   AXI4_ACLK;  // ufix1
  input   AXI4_ARESETN;  // ufix1
  input   [15:0] AXI4_AWID;  // ufix16
  input   [15:0] AXI4_AWADDR;  // ufix16
  input   [7:0] AXI4_AWLEN;  // ufix8
  input   [2:0] AXI4_AWSIZE;  // ufix3
  input   [1:0] AXI4_AWBURST;  // ufix2
  input   AXI4_AWLOCK;  // ufix1
  input   [3:0] AXI4_AWCACHE;  // ufix4
  input   [2:0] AXI4_AWPROT;  // ufix3
  input   AXI4_AWVALID;  // ufix1
  input   [31:0] AXI4_WDATA;  // ufix32
  input   [3:0] AXI4_WSTRB;  // ufix4
  input   AXI4_WLAST;  // ufix1
  input   AXI4_WVALID;  // ufix1
  input   AXI4_BREADY;  // ufix1
  input   [15:0] AXI4_ARID;  // ufix16
  input   [15:0] AXI4_ARADDR;  // ufix16
  input   [7:0] AXI4_ARLEN;  // ufix8
  input   [2:0] AXI4_ARSIZE;  // ufix3
  input   [1:0] AXI4_ARBURST;  // ufix2
  input   AXI4_ARLOCK;  // ufix1
  input   [3:0] AXI4_ARCACHE;  // ufix4
  input   [2:0] AXI4_ARPROT;  // ufix3
  input   AXI4_ARVALID;  // ufix1
  input   AXI4_RREADY;  // ufix1
  input   [31:0] read_ip_timestamp;  // ufix32
  input   signed [31:0] read_AXI_TVS_1000mV;  // sfix32
  input   signed [31:0] read_AXI_TVS_1800mV;  // sfix32
  input   signed [31:0] read_AXI_TVS_2500mV;  // sfix32
  input   signed [31:0] read_AXI_TVS_tempr;  // sfix32
  input   [7:0] read_AXI_SYS_STATUS;  // ufix8
  input   [7:0] read_AXI_PWR_STATUS;  // ufix8
  input   [7:0] read_AXI_PLL_STATUS;  // ufix8
  input   [3:0] read_AXI_I2S_STATUS;  // ufix4
  input   [31:0] read_AXI_CC_SPI_Rd;  // ufix32
  input   [31:0] read_AXI_CC_STATUS;  // ufix32
  input   [31:0] read_AXI_MonADC_STATUS;  // ufix32
  input   [31:0] read_AXI_MonADC_SPI_Rd;  // ufix32
  input   signed [31:0] read_AXI_Mon_12V;  // sfix32
  input   signed [31:0] read_AXI_Mon_1V8;  // sfix32
  input   signed [31:0] read_AXI_Mon_3V3;  // sfix32
  input   signed [31:0] read_AXI_Mon_CurrentIn;  // sfix32
  input   signed [31:0] read_AXI_Mon_VoltageIn;  // sfix32
  input   in_burst_axi4_master_rd;  // ufix1
  input   in_burst_axi4_master_wr;  // ufix1
  output  AXI4_AWREADY;  // ufix1
  output  AXI4_WREADY;  // ufix1
  output  [15:0] AXI4_BID;  // ufix16
  output  [1:0] AXI4_BRESP;  // ufix2
  output  AXI4_BVALID;  // ufix1
  output  AXI4_ARREADY;  // ufix1
  output  [15:0] AXI4_RID;  // ufix16
  output  [31:0] AXI4_RDATA;  // ufix32
  output  [1:0] AXI4_RRESP;  // ufix2
  output  AXI4_RLAST;  // ufix1
  output  AXI4_RVALID;  // ufix1
  output  [31:0] write_AXI4_Master_Rd_base_address;  // ufix32
  output  [31:0] write_AXI4_Master_Wr_base_address;  // ufix32
  output  [31:0] write_AXI_CC_SPI_Wr;  // ufix32
  output  [31:0] write_AXI_CC_CONTROL;  // ufix32
  output  [31:0] write_AXI_PWR_CONTROL;  // ufix32
  output  [31:0] write_AXI_DDR_CONTROL;  // ufix32
  output  [31:0] write_AXI_MonADC_SPI_Wr;  // ufix32
  output  [31:0] write_AXI_MonADC_CONTROL;  // ufix32
  output  [31:0] write_AXI_XAVIER_CONTROL;  // ufix32
  output  soft_reset_pending;  // ufix1
  output  reset_internal;  // ufix1


  wire [31:0] top_data_write;  // ufix32
  wire [13:0] top_addr_sel;  // ufix14
  wire top_wr_enb;  // ufix1
  wire top_rd_enb;  // ufix1
  wire [31:0] top_data_read;  // ufix32
  wire top_reset_internal;  // ufix1


  SYSTEM_ip_addr_decoder u_SYSTEM_ip_addr_decoder_inst (.clk(AXI4_ACLK),  // ufix1
                                                        .reset_x(reset_x),
                                                        .data_write(top_data_write),  // ufix32
                                                        .addr_sel(top_addr_sel),  // ufix14
                                                        .wr_enb(top_wr_enb),  // ufix1
                                                        .rd_enb(top_rd_enb),  // ufix1
                                                        .read_ip_timestamp(read_ip_timestamp),  // ufix32
                                                        .read_AXI_TVS_1000mV(read_AXI_TVS_1000mV),  // sfix32
                                                        .read_AXI_TVS_1800mV(read_AXI_TVS_1800mV),  // sfix32
                                                        .read_AXI_TVS_2500mV(read_AXI_TVS_2500mV),  // sfix32
                                                        .read_AXI_TVS_tempr(read_AXI_TVS_tempr),  // sfix32
                                                        .read_AXI_SYS_STATUS(read_AXI_SYS_STATUS),  // ufix8
                                                        .read_AXI_PWR_STATUS(read_AXI_PWR_STATUS),  // ufix8
                                                        .read_AXI_PLL_STATUS(read_AXI_PLL_STATUS),  // ufix8
                                                        .read_AXI_I2S_STATUS(read_AXI_I2S_STATUS),  // ufix4
                                                        .read_AXI_CC_SPI_Rd(read_AXI_CC_SPI_Rd),  // ufix32
                                                        .read_AXI_CC_STATUS(read_AXI_CC_STATUS),  // ufix32
                                                        .read_AXI_MonADC_STATUS(read_AXI_MonADC_STATUS),  // ufix32
                                                        .read_AXI_MonADC_SPI_Rd(read_AXI_MonADC_SPI_Rd),  // ufix32
                                                        .read_AXI_Mon_12V(read_AXI_Mon_12V),  // sfix32
                                                        .read_AXI_Mon_1V8(read_AXI_Mon_1V8),  // sfix32
                                                        .read_AXI_Mon_3V3(read_AXI_Mon_3V3),  // sfix32
                                                        .read_AXI_Mon_CurrentIn(read_AXI_Mon_CurrentIn),  // sfix32
                                                        .read_AXI_Mon_VoltageIn(read_AXI_Mon_VoltageIn),  // sfix32
                                                        .data_read(top_data_read),  // ufix32
                                                        .write_AXI4_Master_Rd_base_address(write_AXI4_Master_Rd_base_address),  // ufix32
                                                        .write_AXI4_Master_Wr_base_address(write_AXI4_Master_Wr_base_address),  // ufix32
                                                        .write_AXI_CC_SPI_Wr(write_AXI_CC_SPI_Wr),  // ufix32
                                                        .write_AXI_CC_CONTROL(write_AXI_CC_CONTROL),  // ufix32
                                                        .write_AXI_PWR_CONTROL(write_AXI_PWR_CONTROL),  // ufix32
                                                        .write_AXI_DDR_CONTROL(write_AXI_DDR_CONTROL),  // ufix32
                                                        .write_AXI_MonADC_SPI_Wr(write_AXI_MonADC_SPI_Wr),  // ufix32
                                                        .write_AXI_MonADC_CONTROL(write_AXI_MonADC_CONTROL),  // ufix32
                                                        .write_AXI_XAVIER_CONTROL(write_AXI_XAVIER_CONTROL)  // ufix32
                                                        );

  SYSTEM_ip_axi4_module u_SYSTEM_ip_axi4_module_inst (.clk(AXI4_ACLK),  // ufix1
                                                      .AXI4_ARESETN(AXI4_ARESETN),  // ufix1
                                                      .AXI4_AWID(AXI4_AWID),  // ufix16
                                                      .AXI4_AWADDR(AXI4_AWADDR),  // ufix16
                                                      .AXI4_AWLEN(AXI4_AWLEN),  // ufix8
                                                      .AXI4_AWSIZE(AXI4_AWSIZE),  // ufix3
                                                      .AXI4_AWBURST(AXI4_AWBURST),  // ufix2
                                                      .AXI4_AWLOCK(AXI4_AWLOCK),  // ufix1
                                                      .AXI4_AWCACHE(AXI4_AWCACHE),  // ufix4
                                                      .AXI4_AWPROT(AXI4_AWPROT),  // ufix3
                                                      .AXI4_AWVALID(AXI4_AWVALID),  // ufix1
                                                      .AXI4_WDATA(AXI4_WDATA),  // ufix32
                                                      .AXI4_WSTRB(AXI4_WSTRB),  // ufix4
                                                      .AXI4_WLAST(AXI4_WLAST),  // ufix1
                                                      .AXI4_WVALID(AXI4_WVALID),  // ufix1
                                                      .AXI4_BREADY(AXI4_BREADY),  // ufix1
                                                      .AXI4_ARID(AXI4_ARID),  // ufix16
                                                      .AXI4_ARADDR(AXI4_ARADDR),  // ufix16
                                                      .AXI4_ARLEN(AXI4_ARLEN),  // ufix8
                                                      .AXI4_ARSIZE(AXI4_ARSIZE),  // ufix3
                                                      .AXI4_ARBURST(AXI4_ARBURST),  // ufix2
                                                      .AXI4_ARLOCK(AXI4_ARLOCK),  // ufix1
                                                      .AXI4_ARCACHE(AXI4_ARCACHE),  // ufix4
                                                      .AXI4_ARPROT(AXI4_ARPROT),  // ufix3
                                                      .AXI4_ARVALID(AXI4_ARVALID),  // ufix1
                                                      .AXI4_RREADY(AXI4_RREADY),  // ufix1
                                                      .data_read(top_data_read),  // ufix32
                                                      .in_burst_axi4_master_rd(in_burst_axi4_master_rd),  // ufix1
                                                      .in_burst_axi4_master_wr(in_burst_axi4_master_wr),  // ufix1
                                                      .AXI4_AWREADY(AXI4_AWREADY),  // ufix1
                                                      .AXI4_WREADY(AXI4_WREADY),  // ufix1
                                                      .AXI4_BID(AXI4_BID),  // ufix16
                                                      .AXI4_BRESP(AXI4_BRESP),  // ufix2
                                                      .AXI4_BVALID(AXI4_BVALID),  // ufix1
                                                      .AXI4_ARREADY(AXI4_ARREADY),  // ufix1
                                                      .AXI4_RID(AXI4_RID),  // ufix16
                                                      .AXI4_RDATA(AXI4_RDATA),  // ufix32
                                                      .AXI4_RRESP(AXI4_RRESP),  // ufix2
                                                      .AXI4_RLAST(AXI4_RLAST),  // ufix1
                                                      .AXI4_RVALID(AXI4_RVALID),  // ufix1
                                                      .data_write(top_data_write),  // ufix32
                                                      .addr_sel(top_addr_sel),  // ufix14
                                                      .wr_enb(top_wr_enb),  // ufix1
                                                      .rd_enb(top_rd_enb),  // ufix1
                                                      .reset_internal(top_reset_internal),  // ufix1
                                                      .soft_reset_pending(soft_reset_pending)  // ufix1
                                                      );

  assign reset_internal = top_reset_internal;

endmodule  // SYSTEM_ip_axi4

