// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\tb_SYSTEM\SYSTEM_ip_src_SimpleDualPortRAM_generic.v
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// Copyright (c) 2023, Alexei Evsenin, evsenin@gmail.com
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: SYSTEM_ip_src_SimpleDualPortRAM_generic
// Source Path: tb_SYSTEM/SYSTEM/AD7173-8-ADC_0/HDL_FIFO/HDL_FIFO_classic/SimpleDualPortRAM_generic
// Hierarchy Level: 3
// 
// 
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module SYSTEM_ip_src_SimpleDualPortRAM_generic
          (clk,
           wr_din,
           wr_addr,
           wr_en,
           rd_addr,
           rd_dout);

  parameter integer AddrWidth  = 1;
  parameter integer DataWidth  = 1;

  input   clk;
  input   [DataWidth - 1:0] wr_din;  // parameterized width
  input   [AddrWidth - 1:0] wr_addr;  // parameterized width
  input   wr_en;  // ufix1
  input   [AddrWidth - 1:0] rd_addr;  // parameterized width
  output  [DataWidth - 1:0] rd_dout;  // parameterized width


  reg  [DataWidth - 1:0] ram [2**AddrWidth - 1:0];
  reg  [DataWidth - 1:0] data_int;


  always @(posedge clk)
    begin : SimpleDualPortRAM_generic_process
      if (wr_en == 1'b1) begin
        ram[wr_addr] <= wr_din;
      end
      data_int <= ram[rd_addr];
    end

  assign rd_dout = data_int;

endmodule  // SYSTEM_ip_src_SimpleDualPortRAM_generic

