// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\tb_SYSTEM\SYSTEM_ip_src_pulse_10mks.v
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// Copyright (c) 2023, Alexei Evsenin, evsenin@gmail.com
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: SYSTEM_ip_src_pulse_10mks
// Source Path: tb_SYSTEM/SYSTEM/time_stamp_engine/pulse_10mks
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module SYSTEM_ip_src_pulse_10mks
          (clk,
           reset_x,
           PULSE_LEN,
           trigger,
           value,
           valid);


  input   clk;
  input   reset_x;
  input   [15:0] PULSE_LEN;  // uint16
  input   trigger;
  output  [15:0] value;  // uint16
  output  valid;


  wire [15:0] valuedeadOut;  // uint16


  assign value = 16'b0000000000000000;



  SYSTEM_ip_src_Pulse_extender_ctrl u_Pulse_extender_ctrl (.clk(clk),
                                                           .reset_x(reset_x),
                                                           .PULSE_LEN(PULSE_LEN),  // uint16
                                                           .trigger(trigger),
                                                           .valid(valid),
                                                           .value(valuedeadOut)  // uint16
                                                           );
endmodule  // SYSTEM_ip_src_pulse_10mks

